version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: hyper2ch
      MONGO_INITDB_ROOT_USERNAME: hyper2ch
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
